apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: yuehern/user-service:latest  # Replace with the actual image name and tag
        resources:
          limits:
            cpu: "0.5"  # Define the CPU limit (e.g., 0.5 CPU core)
          requests:
            cpu: "0.2"  # Define the CPU request (e.g., 0.2 CPU core)

---
apiVersion: v1
kind: Service
metadata:
  name: user-service-clusterip
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8000  # Port exposed by the container
      targetPort: 8000  # Port the container listens on
  type: ClusterIP  # Create a ClusterIP service
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
spec:
  type: NodePort 
  selector:
    app: user-service
  ports:
    - name: user-service-nodeport-http
      protocol: TCP
      port: 8000  # Port exposed by the container
      targetPort: 8000  # Port the container listens on
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: user-service-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: user-service
  minReplicas: 1  # Minimum number of replicas
  maxReplicas: 10  # Maximum number of replicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 40  # Target average CPU utilization (50%)
