apiVersion: v1
kind: Namespace
metadata:
  name: judge0

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: judge0-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  gcePersistentDisk:
    pdName: judge0-data
    fsType: ext4

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: judge0-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: judge0
  namespace: judge0
spec:
  replicas: 1
  selector:
    matchLabels:
      app: judge0
  template:
    metadata:
      labels:
        app: judge0
    spec:
      containers:
      - name: judge0
        image: judge0/judge0:latest
        ports:
        - containerPort: 2358
        volumeMounts:
        - name: judge0-data
          mountPath: /data
      volumes:
      - name: judge0-data
        persistentVolumeClaim:
          claimName: judge0-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: judge0-service
  namespace: judge0
spec:
  selector:
    app: judge0
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2358
  type: LoadBalancer

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: judge0-ingress
  namespace: judge0
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: judge0-service
            port:
              number: 80
