// constants for api uris

const USERSERVICE_URI = process.env.USER_SERVICE_URL;

export const USER_URI = {
  LOGIN: `${USERSERVICE_URI}/login`,
  REGISTER: `${USERSERVICE_URI}`,
  LOGOUT: `${USERSERVICE_URI}/logout`,
  EDIT: `${USERSERVICE_URI}/edit`,
  DELETE: `${USERSERVICE_URI}`,
  GET_TOKEN: `${USERSERVICE_URI}`,
  VERIFY_TOKEN: `${USERSERVICE_URI}/verify`,
};

const QUESTIONSERVICE_URI = process.env.QUESTION_SERVICE_URL;

export const QUESTION_URI = {
  GET_RANDOM_QUESTION: `${QUESTIONSERVICE_URI}/random/difficulty`,
  GET_BY_ID: `${QUESTIONSERVICE_URI}/id`,
};

export const MATCHINGSERVICE_URI = process.env.MATCHING_SERVICE_URL;

// export const CHATSERVICE_URI = 'http://localhost:3002';
export const CHATSERVICE_URI = process.env.CHAT_SERVICE_URL;

const HISTORYSERVICE_URI = process.env.HISTORY_SERVICE_URL;

export const HISTORY_URI = {
  GET_ALL: `${HISTORYSERVICE_URI}/all`,
  GET_BY_USERNAME: `${HISTORYSERVICE_URI}`,
  CREATE_OR_UPDATE: `${HISTORYSERVICE_URI}/create`,
};
