# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: cs3219-ingress
#   annotations:
#     kubernetes.io/ingress.global-static-ip-name: "web-static-ip"
# spec:
#   rules:
#     - http:
#         paths:
#         - backend:
#             serviceName: user-service-nodeport
#             servicePort: user-service-nodeport-http
#           path: /
#           pathType: Prefix
# ---
# apiVersion: cloud.google.com/v1
# kind: BackendConfig
# metadata:
#   name: userservice-http-hc-config
# spec:
#   healthCheck:
#     checkIntervalSec: 60
#     port: 8000
#     type: HTTP
#     requestPath: /health  
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs3219-ingress
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: user-service-nodeport
                port:
                  number: 8000
          - path: /history
            pathType: Prefix
            backend:
              service:
                name: history-service-nodeport
                port:
                  number: 8000