apiVersion: apps/v1
kind: Deployment
metadata:
  name: history-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: history-service
  template:
    metadata:
      labels:
        app: history-service
    spec:
      containers:
        - name: history-service
          image: yuehern/history-service:latest
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "0.5"  # Maximum CPU limit (0.5 CPU cores)
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:6dXZ2u0kCs@34.118.227.60:5432"

---
apiVersion: v1
kind: Service
metadata:
  name: history-service-service
spec:
  selector:
    app: history-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # Specifies a LoadBalancer service type
