apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  replicas: 1 # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nextjs-app
  template:
    metadata:
      labels:
        app: nextjs-app
    spec:
      containers:
        - name: nextjs-app
          image: yuehern/cs3219peerprep-frontend:latest
          ports:
            - containerPort: 3000 # Adjust the container port if your Next.js app uses a different port
          env:
            - name: USER_SERVICE_URL
              value: "http://35.227.201.105"
            - name: QUESTION_SERVICE_URL
              value: "http://35.227.201.105"
            - name: MATCHING_SERVICE_URL
              value: "http://35.227.201.105"
            - name: CHAT_SERVICE_URL
              value: "http://35.227.201.105"
            - name: HISTORY_SERVICE_URL
              value: "http://35.227.201.105"
---
apiVersion: v1
kind: Service
metadata:
  name: nextjs-nodeport
spec:
  type: NodePort 
  selector:
    app: nextjs-app
  ports:
    - name: nextjs-nodeport-http
      protocol: TCP
      port: 3000  # Port exposed by the container
      targetPort: 3000  # Port the container listens on
